# Theme
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

# Site Settings
title: "The Art of Quality Library"
subtitle: "A curated collection of ideas worth revisiting"
name: "Your Name"
description: "A digital library focused on timeless knowledge, clear thinking, and intellectual craftsmanship."
url: "https://rranch252.github.io"
baseurl: "/TAOQ"
repository: "rranch252/TAOQ"

# Site Author
author:
  name: "Your Name"
  bio: "Curator of timeless ideas"
  location: "Ireland"

# Reading Files
include:
  - _pages

# Collections
collections:
  books:
    output: true
    permalink: /:collection/:path/
  essays:
    output: true
    permalink: /:collection/:path/
  notes:
    output: true
    permalink: /:collection/:path/
  guides:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: true
      share: false
      related: true
  # _books
  - scope:
      path: ""
      type: books
    values:
      layout: single
      author_profile: false
      share: false
      sidebar:
        nav: "books"
  # _essays
  - scope:
      path: ""
      type: essays
    values:
      layout: single
      author_profile: false
      share: false

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Minimal Mistakes Settings
minimal_mistakes_skin: "air" # "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
search: true
