# Site settings
title: The Art of Quality Library
description: A curated collection of ideas worth revisiting
author: Your Name
baseurl: "/TAOQ"
url: "https://rranch252.github.io"

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Collections
collections:
  books:
    output: true
    permalink: /books/:title/
  essays:
    output: true
    permalink: /essays/:title/
  notes:
    output: true
    permalink: /notes/:title/
  guides:
    output: true
    permalink: /guides/:title/

# Exclude files
exclude:
  - README.md
  - package.json
  - package-lock.json
  - node_modules
